# Note: 
The test set provided does not include the target variable which is 'clicked'. In this case, the results of the predictions using this set cannot be confirmed but still predicted with approximately 95% precision accuracy.
The results obtained are a translations of the possible probabilities of the predictions, i.e, if the result is 1 means that the probability that the ad is clicked is equal or superior than 50% and, in the second case, if the result is 0 then the probability of a clicked ad is inferior than 50%.  
    
    

In [1]:
import numpy as np
import pandas as pd

import os

from sklearn.model_selection import train_test_split

from sklearn import metrics


%matplotlib inline

In [2]:
# Read in the data.
df_test = pd.read_csv('test.csv', sep= ',')

C:\Users\xps\anaconda3\envs\Need\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


EDA

In [3]:
df_test

timestamp                     bidid  \
0       1430264861  VUAbtwAKfUwKG+JOugBfTw==   
1       1430264862  VUAbuAANjzkKwo3v1AB++g==   
2       1430264862  VUAbuQAA39MKwuUk0wBMBQ==   
3       1430264862  VUAbuQAB6HoKG+HGlQAW1w==   
4       1430264862  VUAbuQAJO6cKGxPLvQB1Sw==   
...            ...                       ...   
508153  1430412589  VUJcxgAOcawKG+KQPQAQWA==   
508154  1430412589  VUJcxwAAEmkKG4/BhAA7Xg==   
508155  1430412589  VUJcxwAAYWQK24QjGwAhRQ==   
508156  1430412589  VUJcxwABiGMKwmLz0gBrAA==   
508157  1430412589  VUJcxwABf5MKG+PWRABp2g==   

                                   device_id                      user_id  \
0       20189672-3ca0-48f8-957f-b2400005fea2  CAESEO1swnwzbyP_ulp5I6dwI9w   
1       8f46fac0-8893-4547-8ec7-028b4812057a  CAESEMgZsfgjSKT7GvZNAtFJaAs   
2       692cb285-3ed0-4294-afda-fefb7a877238  CAESECYlSHMNcbKaLUtv2aXuBYw   
3       81f53cbd-0a22-4b94-87fb-8f3f4ef8148f  CAESEIM8HpwwPdYg_1FhZwa9sHo   
4       cab4ae17-6b48-483e-ba68-ad49c8d944a0  CAESEK2HiR6F1ncLdKqp_F6vOF8   
...                                      ...                          ...   
508153  fd39d6de-dd1a-4ceb-a66c-c65f7c33586d  CAESEDa6sg5UTPEJwHLWU0wS2Zs   
508154  36e3110e-814a-46ac-8895-83012a2b14c9  CAESEP1c-lretBLLZbJYCUW74sU   
508155  9535148b-fdc2-4457-8421-b76bd370b785  CAESELPmjVEZqLnKLU99IEvRj-k   
508156  39bcabde-b58d-42e3-a667-ada6cb401592  CAESEBdDyltFBAn9ZVJDRduE87k   
508157  eaf378c1-a23e-46ce-a091-925aa7f8e284  CAESELksfMhdW8yU2-B2dzb8PIY   

         format   bidfloor support_type   support_id  device_type device_os  \
0       320x480    1000000          app    606697013            1       ios   
1       320x480    1000000          app    905455244            1       ios   
2       320x480  197000000          app    623367437            1       ios   
3       320x480  198000000          app    911152486            1       ios   
4       320x480    1000000          app    506916707            1       ios   
...         ...        ...          ...          ...          ...       ...   
508153  320x480    1000000          app  536931657.0            1       ios   
508154  320x480    1000000          app  421576027.0            1       ios   
508155  320x480  185000000          app  911793120.0            1       ios   
508156  320x480    1000000          app  893530727.0            1       ios   
508157  320x480  185000000          app  911793120.0            1       ios   

       device_language device_model  verticals_0  verticals_1  verticals_2  \
0                en_EN       iphone          675         1462            0   
1                fr_FR       iphone          926         1462         1536   
2                fr_FR       iphone         1494         1462          105   
3                fr_FR       iphone          937          926         1462   
4                en_EN       iphone          386          384           13   
...                ...          ...          ...          ...          ...   
508153           fr_FR       iphone           39         1462         1071   
508154           fr_FR       iphone          926         1462            0   
508155           fr_FR       iphone          937         1462         1536   
508156           fr_FR       iphone          220         1462           35   
508157           fr_FR       iphone          937         1462         1536   

        vertical_3   ad_id  bid_price  won_price  
0                0  544501  220000000  184000000  
1             1071  544477  220000000  198000000  
2              937  544501  220000000  197000000  
3             1536  544501  220000000  208000000  
4             1379  544501  220000000  107000000  
...            ...     ...        ...        ...  
508153           8  544501  200000000   99000000  
508154           0  544501  200000000  184000000  
508155        1461  544501  380000000  185000000  
508156          78  544501  200000000   97000000  
508157        1461  544501  380000000  230000000  

[508158 

In [4]:
df_test.columns

Index(['timestamp', 'bidid', 'device_id', 'user_id', 'format', 'bidfloor',
       'support_type', 'support_id', 'device_type', 'device_os',
       'device_language', 'device_model', 'verticals_0', 'verticals_1',
       'verticals_2', 'vertical_3', 'ad_id', 'bid_price', 'won_price'],
      dtype='object')

In [5]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 508158 entries, 0 to 508157
Data columns (total 19 columns):
 #   Column           Non-Null Count   Dtype 
---  ------           --------------   ----- 
 0   timestamp        508158 non-null  int64 
 1   bidid            508158 non-null  object
 2   device_id        508158 non-null  object
 3   user_id          508158 non-null  object
 4   format           508158 non-null  object
 5   bidfloor         508158 non-null  int64 
 6   support_type     508158 non-null  object
 7   support_id       508158 non-null  object
 8   device_type      508158 non-null  int64 
 9   device_os        508158 non-null  object
 10  device_language  508158 non-null  object
 11  device_model     508158 non-null  object
 12  verticals_0      508158 non-null  int64 
 13  verticals_1      508158 non-null  int64 
 14  verticals_2      508158 non-null  int64 
 15  vertical_3       508158 non-null  int64 
 16  ad_id            508158 non-null  int64 
 17  bid_price 

In [6]:
#check columns with nan values
df_test.columns[df_test.isna().any()]

Index([], dtype='object')

In [7]:
df_test.isnull().sum()

timestamp          0
bidid              0
device_id          0
user_id            0
format             0
bidfloor           0
support_type       0
support_id         0
device_type        0
device_os          0
device_language    0
device_model       0
verticals_0        0
verticals_1        0
verticals_2        0
vertical_3         0
ad_id              0
bid_price          0
won_price          0
dtype: int64

In [8]:
df_test.describe()

timestamp      bidfloor  device_type    verticals_0    verticals_1  \
count  5.081580e+05  5.081580e+05     508158.0  508158.000000  508158.000000   
mean   1.430358e+09  9.823643e+07          1.0     744.735169    1060.074205   
std    4.597176e+04  8.478177e+07          0.0     643.726555     575.610727   
min    1.430265e+09  1.000000e+06          1.0       0.000000       0.000000   
25%    1.430314e+09  1.000000e+06          1.0     220.000000     901.000000   
50%    1.430384e+09  1.280000e+08          1.0     926.000000    1462.000000   
75%    1.430395e+09  1.880000e+08          1.0     937.000000    1462.000000   
max    1.430413e+09  2.760000e+08          1.0    5693.000000    5200.000000   

         verticals_2     vertical_3          ad_id     bid_price     won_price  
count  508158.000000  508158.000000  508158.000000  5.081580e+05  5.081580e+05  
mean      814.250910     702.113612  544493.477052  2.410010e+08  1.783978e+08  
std       649.215254     643.740032       8.400720  6.563184e+07  5.201003e+07  
min         0.000000       0.000000  544474.000000  1.000000e+08 -1.000000e+05  
25%       105.000000       0.000000  544489.000000  2.000000e+08  1.720000e+08  
50%      1071.000000     937.000000  544501.000000  2.200000e+08  1.850000e+08  
75%      1462.000000    1461.000000  544501.000000  2.200000e+08  1.970000e+08  
max      5527.000000    1611.000000  544501.000000  3.800000e+08  3.800000e+08

In [9]:
df_test.support_type.unique()

array(['app', 'website'], dtype=object)

In [10]:
df_test['support_type']= df_test['support_type'].replace(["app", "website"],[0,1] )

In [11]:
df_test.device_os.unique() #device os is always ios so no need to keep it!

array(['ios'], dtype=object)

In [12]:
df_test.drop("device_os",axis=1, inplace= True)

In [13]:
df_test.device_type.unique() #device type is always 1 so all the study is based on one type device!

array([1], dtype=int64)

In [14]:
df_test.drop("device_type",axis=1, inplace= True) 

In [15]:
df_test.device_language.unique()

array(['en_EN', 'fr_FR', 'ko_KO', 'ru_RU', 'tr_TR', 'ja_JA', 'th_TH',
       'zh_CN', 'ro_RO', 'pt_PT', 'es_ES', 'pl_PL', 'it_IT', 'de_DE',
       'ar_AR', 'nl_NL', 'km_KM', 'zh_TW', 'hr_HR', 'el_EL', 'sv_SV',
       'da_DA', 'iw_IW', 'hu_HU', 'vi_VI', 'ta_TA', 'no_NO', 'fa_FA',
       'co_CO', 'ca_CA', 'ln_LN', 'eu_EU', 'uk_UK', 'cs_CS', 'bn_BN',
       'fi_FI', 'pa_PA', 'sq_SQ', 'ht_HT', 'sk_SK', 'gu_GU', 'hy_HY',
       'bg_BG', 'kn_KN', 'yi_YI', 'la_LA', 'sh_SH', 'lo_LO', 'mg_MG',
       'ka_KA', 'br_BR', 'mn_MN', 'bs_BS'], dtype=object)

In [16]:
df_test['device_language']= df_test['device_language'].replace(['en_EN', 'fr_FR', 'ko_KO', 'ru_RU', 'tr_TR', 'ja_JA', 'th_TH',
       'zh_CN', 'ro_RO', 'pt_PT', 'es_ES', 'pl_PL', 'it_IT', 'de_DE',
       'ar_AR', 'nl_NL', 'km_KM', 'zh_TW', 'hr_HR', 'el_EL', 'sv_SV',
       'da_DA', 'iw_IW', 'hu_HU', 'vi_VI', 'ta_TA', 'no_NO', 'fa_FA',
       'co_CO', 'ca_CA', 'ln_LN', 'eu_EU', 'uk_UK', 'cs_CS', 'bn_BN',
       'fi_FI', 'pa_PA', 'sq_SQ', 'ht_HT', 'sk_SK', 'gu_GU', 'hy_HY',
       'bg_BG', 'kn_KN', 'yi_YI', 'la_LA', 'sh_SH', 'lo_LO', 'mg_MG',
       'ka_KA', 'br_BR', 'mn_MN', 'bs_BS'],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52] )

In [17]:
df_test.device_model.unique()

array(['iphone', 'ipod'], dtype=object)

In [18]:
df_test['device_model']= df_test['device_model'].replace(["iphone", "ipod"],[0,1] )

In [19]:
df_test.ad_id.unique()

array([544501, 544477, 544489, 544474], dtype=int64)

In [20]:
df_test['ad_id']= df_test['ad_id'].replace([544501, 544477, 544489, 544474],[0,1,2,3] )

In [21]:
df_test.bid_price.unique()

array([220000000, 300000000, 380000000, 200000000, 100000000], dtype=int64)

In [22]:
df_test['bid_price']= df_test['bid_price'].replace([220000000, 300000000, 380000000, 200000000, 100000000],[2,3,4,1,0] )

In [23]:
len(df_test.bidid.unique()) #bidid to remove because it is independent

508158

In [25]:
len(df_test.timestamp.unique()) #we need it

109957

In [26]:
len(df_test.won_price.unique()) #we need it

380

In [27]:
len(df_test.verticals_0.unique())

294

In [28]:
len(df_test.user_id.unique())

214824

In [29]:
#same 'format' over the whole dataset, no need in the training process

In [30]:
df_test.drop("bidid",axis=1, inplace= True)
df_test.drop("format",axis=1, inplace= True)
df_test.drop("user_id",axis=1, inplace= True)
df_test.drop("device_id",axis=1, inplace= True)

In [ ]:
#check for None values
#for c in df_test.columns:
#    k=0
#    for i in range (0,len(x['timestamp'])):
#        if df_test[c][i] == 'None': k+=1 
#    print(c,':',k)
        

In [31]:
len(df_test.support_id.unique())

4055

In [32]:
df_test['support_id'].value_counts() #the most frequent support_id is 623367437

484115113.0    42997
905852173.0    33495
911793120.0    33125
623367437      25749
951364656.0    22741
               ...  
867991872.0        1
833585422.0        1
766504466          1
640450806.0        1
513273934          1
Name: support_id, Length: 4055, dtype: int64

In [33]:
for i in range (0,len(df_test['timestamp'])):
        if df_test['support_id'][i] == 'None': df_test['support_id'][i] = 623367437
    

<ipython-input-33-e47f07a58858>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if df_test['support_id'][i] == 'None': df_test['support_id'][i] = 623367437


In [34]:
k=0
for i in range (0,len(df_test['timestamp'])):
    if df_test['support_id'][i] == 'None': k+=1 
print(k)
        

0


In [35]:
#Normalizing the data manually:

In [36]:
df_test['timestamp']=(df_test['timestamp']-min(df_test.timestamp))/(max(df_test.timestamp)-min(df_test.timestamp))

In [37]:
df_test['bidfloor']=(df_test['bidfloor']-min(df_test.bidfloor))/(max(df_test.bidfloor)-min(df_test.bidfloor))

In [38]:
df_test['support_id'] = df_test['support_id'].astype(int)

In [39]:
df_test['support_id']=(df_test['support_id']-min(df_test.support_id))/(max(df_test.support_id)-min(df_test.support_id))

In [40]:
df_test.support_id

0         0.457681
1         0.883787
2         0.481457
3         0.891913
4         0.315369
            ...   
508153    0.358178
508154    0.193651
508155    0.892827
508156    0.866780
508157    0.892827
Name: support_id, Length: 508158, dtype: float64

In [41]:
df_test['device_language']=(df_test['device_language']-min(df_test.device_language))/(max(df_test.device_language)-min(df_test.device_language))

In [42]:
df_test['verticals_0']=(df_test['verticals_0']-min(df_test.verticals_0))/(max(df_test.verticals_0)-min(df_test.verticals_0))

In [43]:
df_test['verticals_1']=(df_test['verticals_1']-min(df_test.verticals_1))/(max(df_test.verticals_1)-min(df_test.verticals_1))

In [44]:
df_test['verticals_2']=(df_test['verticals_2']-min(df_test.verticals_2))/(max(df_test.verticals_2)-min(df_test.verticals_2))

In [45]:
df_test['vertical_3']=(df_test['vertical_3']-min(df_test.vertical_3))/(max(df_test.vertical_3)-min(df_test.vertical_3))

In [46]:
df_test['ad_id']=(df_test['ad_id']-min(df_test.ad_id))/(max(df_test.ad_id)-min(df_test.ad_id))
df_test['bid_price']=(df_test['bid_price']-min(df_test.bid_price))/(max(df_test.bid_price)-min(df_test.bid_price))
df_test['won_price']=(df_test['won_price']-min(df_test.won_price))/(max(df_test.won_price)-min(df_test.won_price))

In [47]:
df_test

timestamp  bidfloor  support_type  support_id  device_language  \
0        0.000000  0.000000             0    0.457681         0.000000   
1        0.000007  0.000000             0    0.883787         0.019231   
2        0.000007  0.712727             0    0.481457         0.019231   
3        0.000007  0.716364             0    0.891913         0.019231   
4        0.000007  0.000000             0    0.315369         0.000000   
...           ...       ...           ...         ...              ...   
508153   1.000000  0.000000             0    0.358178         0.019231   
508154   1.000000  0.000000             0    0.193651         0.019231   
508155   1.000000  0.669091             0    0.892827         0.019231   
508156   1.000000  0.000000             0    0.866780         0.019231   
508157   1.000000  0.669091             0    0.892827         0.019231   

        device_model  verticals_0  verticals_1  verticals_2  vertical_3  \
0                  0     0.118567     0.281154     0.000000    0.000000   
1                  0     0.162656     0.281154     0.277908    0.664804   
2                  0     0.262428     0.281154     0.018998    0.581626   
3                  0     0.164588     0.178077     0.264520    0.953445   
4                  0     0.067803     0.073846     0.002352    0.855990   
...              ...          ...          ...          ...         ...   
508153             0     0.006851     0.281154     0.193776    0.004966   
508154             0     0.162656     0.281154     0.000000    0.000000   
508155             0     0.164588     0.281154     0.277908    0.906890   
508156             0     0.038644     0.281154     0.006333    0.048417   
508157             0     0.164588     0.281154     0.277908    0.906890   

           ad_id  bid_price  won_price  
0       0.000000       0.50   0.484346  
1       0.333333       0.50   0.521179  
2       0.000000       0.50   0.518548  
3       0.000000       0.50   0.547488  
4       0.000000       0.50   0.281768  
...          ...        ...        ...  
508153  0.000000       0.25   0.260721  
508154  0.000000       0.25   0.484346  
508155  0.000000       1.00   0.486977  
508156  0.000000       0.25   0.255459  
508157  0.000000       1.00   0.605367  

[508158 rows x 13 columns]

In [48]:
df_test.columns

Index(['timestamp', 'bidfloor', 'support_type', 'support_id',
       'device_language', 'device_model', 'verticals_0', 'verticals_1',
       'verticals_2', 'vertical_3', 'ad_id', 'bid_price', 'won_price'],
      dtype='object')

In [49]:
#use the saved model

In [50]:
import pickle

In [51]:
# load the model from disk.
loaded_model = pickle.load(open('model.pkl', 'rb'))


In [52]:
X_test= df_test[['timestamp', 'bidfloor',
       'support_type', 'support_id', 'device_language', 'device_model',
       'verticals_0', 'verticals_1', 'verticals_2', 'vertical_3', 'ad_id',
       'bid_price', 'won_price']]


In [53]:
Y_test = loaded_model.predict(X_test)

In [54]:
Y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)